# Generated by Django 3.2.4 on 2021-06-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0002_address_country_document_emailidentity_emailuserro_invoice_privatedocument_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=4)),
                ('custom_ledger', models.BooleanField(default=False)),
                ('booking_reference', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open - currently active'), ('Merged', 'Merged - superceded by another basket'), ('Saved', 'Saved - for items to be purchased later'), ('Frozen', 'Frozen - the basket cannot be modified'), ('Submitted', 'Submitted - has been ordered at the checkout')], default='Open', max_length=128, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_merged', models.DateTimeField(blank=True, null=True, verbose_name='Date merged')),
                ('date_submitted', models.DateTimeField(blank=True, null=True, verbose_name='Date submitted')),
            ],
            options={
                'db_table': 'basket_basket',
                'managed': False,
            },
        ),
    ]
