# Generated by Django 3.2.10 on 2022-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ledger_api_client', '0003_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='ledger_api_permissions')),
            ],
            options={
                'verbose_name': 'ledger_api_group',
                'verbose_name_plural': 'ledger_api_groups',
            },
        ),
    ]
