# Generated by Django 3.2.10 on 2022-01-25 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0004_systemgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemgroup',
            options={'verbose_name': 'System Group', 'verbose_name_plural': 'System Groups'},
        ),
        migrations.CreateModel(
            name='SystemGroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('emailuser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('system_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger_api_client.systemgroup')),
            ],
        ),
    ]
