# Generated by Django 3.2.25 on 2024-07-29 12:22

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0006_systemuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('residential_address', 'Residential Address'), ('postal_address', 'Postal Address'), ('billing_address', 'Billing Address')], max_length=50, null=True)),
                ('line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 2')),
                ('line3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 3')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb / Town')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, default='WA', max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='AU', max_length=2, null=True)),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_api_client.systemuser')),
            ],
        ),
    ]
