# Generated by Django 3.2.25 on 2024-07-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0007_systemaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemAddress',
            new_name='SystemUserAddress',
        ),
    ]
