# Generated by Django 3.2.25 on 2024-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0009_auto_20240802_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='account_change_locked',
            field=models.BooleanField(default=False, help_text='Will lock the account details preventing changes to the account information.'),
        ),
    ]
