# Generated by Django 5.0.8 on 2024-08-27 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0011_systemgroup_description_alter_datastore_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='ledger_id',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
