# Generated by Django 5.0.8 on 2024-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0012_alter_systemuser_ledger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuseraddress',
            name='system_address_link',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemuseraddress',
            name='use_for_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuseraddress',
            name='use_for_postal',
            field=models.BooleanField(default=False),
        ),
    ]
