# Generated by Django 5.0.8 on 2024-09-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0013_systemuseraddress_system_address_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUserChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('change_value', models.CharField(blank=True, max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('change_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_log_request_user', to='ledger_api_client.systemuser')),
                ('systemuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_log_system_user', to='ledger_api_client.systemuser')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
