# Generated by Django 5.0.8 on 2024-09-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0014_systemuserchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Given name(s)'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Last name'),
        ),
    ]
