# Generated by Django 5.0.8 on 2024-11-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_api_client', '0016_systemuser_prevent_auto_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='prevent_auto_locked',
            new_name='prevent_auto_lock',
        ),
    ]
